-- AlterTable
ALTER TABLE `User` ADD COLUMN `selfReferrerBonusAwarded` BOOLEAN NOT NULL DEFAULT false;

-- AlterEnum PointRuleKey
ALTER TABLE `PointRule` MODIFY `key` ENUM('BASE_REGISTRATION', 'CORRECT_PREDICTION', 'WRONG_PREDICTION', 'REFERRAL_SUCCESS', 'SELF_REFERRER_CLAIM', 'CANCELLED_MATCH') NOT NULL;

-- AlterEnum PointTransactionType
ALTER TABLE `PointTransaction` MODIFY `type` ENUM('BASE_REGISTRATION', 'CORRECT_PREDICTION', 'WRONG_PREDICTION', 'REFERRAL_SUCCESS', 'SELF_REFERRER_CLAIM', 'ADMIN_ADJUSTMENT', 'RESETTLEMENT') NOT NULL;
